### ISSUE TITLE
"create opinion" turns into "edit opinion"

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#69]
**Is your feature request related to a problem? Please describe.**
A user can only post one statement/publish one opinion per topic. Yet after he created an opinion, he is still presented with the "create opinion" button. If he clicks it, an error is triggered. We need to catch this error. 

We also need to move buttons out of the 3d engine. 

**Describe the solution you'd like**
If the user published an opinion in a topic, the "create opinion" button is changed to an "edit" icon/button.
it replaces the old "edit" button, that was positioned/floating around in the 3d engine.

**Comment by ozFri** [comment]
Rephrasing:
Currently In order to create an opinion the user clicks on a "create opinion" icon in the action menu.
After the opinion is created, the "create opinion" button stays, but it is not functioning.
After creating a new opinion, it can be edited by clicking an edit icon on the opinion itself.
To keep the UI uniform, we want to move the edit action to the menu, and remove the "create opinion"
button from this context, after the opinion was created.

**Comment by Iwan-Ittermann** [comment]
perfectly worded

**Comment by Iwan-Ittermann** [comment]
if the old version of the opinion could be stored in the database, that would be great. We want to show the opinion history in the future.

**Comment by avirankatzsofi** [comment]
Done in 14b6520.

**Comment by Iwan-Ittermann** [comment]
The button in the tool bar needs to change, so the user notices he can edit his opinion. Any kind of typical edit icon ("pencil") would do.

**Comment by avirankatzsofi** [comment]
It would be a bit time-consuming to alter the icon based on the context given the current code and timetable. 
Could we go with one of them (`pencil`/`chat bubble`) for both cases?

**Comment by Iwan-Ittermann** [comment]
How about a quick and dirty layer?

**Comment by avirankatzsofi** [comment]
Done and visible at https://demo.dpt.world
Closing for now (@Iwan-Ittermann  feel free to reopen if needed)
